name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change this to the branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add this step only if you need to build your project
      - name: Build project
        run: |
          # Add your build commands here if needed
          # Example: npm install && npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./documentation  # Change this to your actual output directory

      - name: Output Deployment URL
        run: echo "Deployment URL: https://michaelildefonso.github.io/Hashing-Algorithm/documentation/index.html"
